### ISSUE TITLE
该项目如何使用

### ISSUE THREAD

**Issue by bloatfan** [ybw2016v/wxdog#2]
您好、想请教一下、该项目如何自己部署使用

addogs 时、那个 c 和 i 参数是啥

**Comment by ybw2016v** [comment]
> 您好、想请教一下、该项目如何自己部署使用
> 
> addogs 时、那个 c 和 i 参数是啥

这个项目写了一半，没写完……这段时间有其他事情，估计要到七月底才能继续搞

flask的部署方式很灵活，在不同的服务器环境下有不同的方式，具体可以参考flask的文档
https://dormousehole.readthedocs.io/en/latest/deploying/index.html

i是用户的token c是微信公众号文章永久链接/s/之后的部分……

**Comment by bloatfan** [comment]
> > 您好、想请教一下、该项目如何自己部署使用
> > addogs 时、那个 c 和 i 参数是啥
> 
> 这个项目写了一半，没写完……这段时间有其他事情，估计要到七月底才能继续搞
> 
> flask的部署方式很灵活，在不同的服务器环境下有不同的方式，具体可以参考flask的文档
> https://dormousehole.readthedocs.io/en/latest/deploying/index.html
> 
> i是用户的token c是微信公众号文章永久链接/s/之后的部分……

好的、我关注一下、等你写完了、我在研究研究 👍

**Comment by ybw2016v** [comment]
这几个月有点忙，保守估计要十月份之后才能继续搞了……
